module.exports = {
  siteMetadata: {
    htmlLang: 'en',
    contenLang: 'de-DE',
    title: 'inriva Hilfeportal',
    titleTemplate: '%s · Hilfe',
    description: 'inriva Hilfecenter',
    siteUrl: 'https://help.inriva.com',
    siteName: 'An dieser Stelle haben wir für Sie sowohl häufig gestellte Fragen als auch Anleitungen bereitgestellt. Sollten Sie weitere Fragen haben oder Inhalte vermissen, sprechen Sie uns einfach per Chat oder E-Mail direkt an.',
    logoUrl: '/images/logo.png',
    logoLabel: 'Hilfeportal',
    searchText: 'Suche',
    faviconUrl: '/images/favicon.png',
    socialSharingImageUrl: '/images/social-sharing-preview.png',
    twitter: '@inrivagmbh',
    facebookUrl: 'https://www.facebook.com/inrivagmbh',
    ctaButtonText: 'Anfrage erstellen',
    ctaButtonUrl: 'mailto:support@inriva.com',
    linkText: 'Zum Karriereportal',
    linkUrl: 'https://www.inriva.com',
    headline: 'Wie können wir helfen?',
    footerText: 'Zurück',
    footerUrl: 'https://www.inriva.com',
    googleTagManagerId: '',
    googleAnalyticsMeasurementId: '',
  },
  plugins: ['gatsby-plugin-typescript', '@mlent/gatsby-theme-help-center'],
};
